version: '3.8'

services:
  ingredient-analyzer:
    image: ingredient-analyzer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./media:/app/media